spring.application.name=torneo-verano

# Render te asignará un puerto automáticamente. Si no estás en Render, usa el 8081.
server.port=${PORT:8081}

# Configuración de Base de Datos Dinámica
# Si existen estas variables (en Render), usará PostgreSQL. Si no (en tu PC), usará H2.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:torneodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

# JPA & Hibernate Settings (Crea y actualiza las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Consola H2 para cuando estés en local
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console